= Ruby Belgeleri
YazBel Topluluğu
0.1, 13 Mayıs, 2017, YazBel Ruby Belgeleri
:version-label: Sürüm
:last-update-label: Son güncelleme
:icons: font
:source-highlighter: pygments
:source-language: ruby
:toc: left
:toc-title: İçindekiler

// Font simgelerinin çalışması için eklenmiştir.
++++
<script src="https://use.fontawesome.com/c38eb8c034.js"></script>
++++

Ruby belgelerine hoşgeldiniz!

[WARNING]
====
Buradaki belgeler henüz çok yenidir ve yardımınıza ihtiyaç duymaktadır.
Bu belgeler topluluk tarafından geliştirildikçe gelişecektir.
Lütfen aşağıda anlatıldığı şekilde belgelere katkıda bulununuz.
====

== Belgeler Hakkında

Bu belgelerin kaynak kodu https://github.com/yazbel/belgeler[GitHub'ta tutulmaktadır].

=== Nasıl yardım alabilirim?

Her zaman https://forum.yazbel.com/[YazBel forumu]nun https://forum.yazbel.com/c/ruby[Ruby kategorisi]nde bir konu açarak aklınızdaki soruları sorabilirsiniz.
Topluluk size yardım etmekten mutluluk duyacaktır.

=== Nasıl yardım edebilirim?

Birçok şekilde yardım edebilirsiniz:

- Belgelerde değişiklik yaparak çekme isteği(pull request) gönderebilirsiniz.
Yazım yanlışları ve küçük hatalar için GitHub arayüzünü kullanabilirsiniz ancak daha büyük ve karmaşık düzeltmeler için veri havuzunu bilgisayarınıza çekmeli, daha sonrasında düzeltmeleri yapıp çekme isteği göndermelisiniz.
Her iki durumda da kısa ve öz bir işleme mesajı(commit message) yazdığınıza emin olmalısınız.

- Eğer bir yanlış gördünüz ancak bir sebepten ötürü düzeltmeyi kendiniz yapmak istemediyseniz, bu hatayı bildirerek de yardım edebilirsiniz.
Bunun için veri havuzunun https://github.com/yazbel/belgeler/issues[konular(issues)] dizininde bir konu açın, başlık ve açıklama kısmına ilgili metinleri yazın ve gönderin.
Başlık kısmının kısa ve öz olmasına dikkat edin.
Ayrıca konuya, sağ taraftaki **Labels** bölümünden `ruby` etiketini eklediğinize de emin olun.

- https://forum.yazbel.com/c/ruby[Forumun Ruby kategorisi]nde sorulan soruları cevaplayabilirsiniz.

=== Lisans

https://github.com/yazbel/belgeler/blob/master/LICENSE[`LICENSE`] dosyasında da belirtildiği üzere bu belgelerin lisansı *Creative Commons Atıf-GayriTicari-AynıLisanslaPaylaş 4.0 Uluslararası (CC BY-NC-SA 4.0)* lisansıdır.
Daha fazla bilgi için lütfen dosyanın içeriğine bakınız.

== Ruby Hakkında

https://www.ruby-lang.org/tr/[Ruby], https://tr.wikipedia.org/wiki/Yukihiro_Matsumoto[Yukihiro Matsumoto] tarafından 1993 yılında Japonya'da tasarlanmaya ve geliştirilmeye başlanmıştır.
Verimlilik ve sadelik üzerine odaklanmış, açık kaynak kodlu dinamik bir dildir.
Okumayı ve yazmayı kolaylaştıran, doğal bir sözdizimine sahiptir.
Ayrıca günümüzün gözde programlama paradigmalarından olan nesneye yönelik programlama ve fonksiyonel programlama paradigmalarını güçlü bir şekilde desteklemektedir.
Ruby özgür bir yazılımdır ve https://www.ruby-lang.org/en/about/license.txt[Ruby lisansı] ile lisanslanmıştır.

== Kurulum

Ruby'nin farklı işletim sistemlerinde farklı kurulumları vardır:

=== Windows

Ruby'yi Windows'a kurmanın en iyi yolu https://rubyinstaller.org/[RubyInstaller]'ı kullanmaktır.
Siteye girip *Download* tuşuna basın ve en son Ruby sürümünü içeren kurucuyu indirip kurun.

=== Mac OS X

Mac OS X'te Ruby zaten kurulu gelmektedir, bu yüzden herhangi bir kuruluma gerek yoktur.

=== GNU/Linux

Ruby'yi GNU/Linux sisteminize paket yöneticileri aracılığıyla kolayca kurabilirsiniz:

* *Debian, Ubuntu*
+
----
$ sudo apt-get install ruby-full
----
* *CentOS, Fedora, RHEL*
+
----
$ sudo yum install ruby
----
* *Gentoo*
+
----
$ sudo emerge dev-lang/ruby
----
* *Arch Linux*
+
----
$ sudo pacman -S ruby
----

Kurulumdan sonra şu komutla kurulumu doğrulayabilirsiniz:

----
$ ruby --version
----

Bu komut sisteminizde kurulu Ruby sürümünü çıktı olarak vermelidir.
Eğer bunun yerine bir hata alıyorsanız yukarıdaki kurulum adımlarını tekrarlamalısınız.

== Kılavuz

Kısa ve öz olarak yazılmış link:kilavuz/[bu kılavuz] ile adım adım ilerleyerek Ruby uygulama geliştirmeyi öğrenin!
