= Beautiful Soup Belgeleri
YazBel Topluluğu
0.1, 13 Mayıs, 2017, YazBel Beautiful Soup Belgeleri
:version-label: Sürüm
:last-update-label: Son güncelleme
:icons: font
:source-highlighter: pygments
:source-language: python
:toc: left
:toc-title: İçindekiler

// Font simgelerinin çalışması için eklenmiştir.
++++
<script src="https://use.fontawesome.com/c38eb8c034.js"></script>
++++

Beautiful Soup belgelerine hoşgeldiniz!

[WARNING]
====
Buradaki belgeler henüz çok yenidir ve yardımınıza ihtiyaç duymaktadır.
Bu belgeler topluluk tarafından geliştirildikçe gelişecektir.
Lütfen aşağıda anlatıldığı şekilde belgelere katkıda bulununuz.
====

== Belgeler Hakkında

Bu belgelerin kaynak kodu https://github.com/yazbel/belgeler[GitHub'ta tutulmaktadır].

=== Nasıl yardım alabilirim?

Her zaman https://forum.yazbel.com/[YazBel forumu]nun https://forum.yazbel.com/c/python/beautiful-soup[Beautiful Soup kategorisi]nde bir konu açarak aklınızdaki soruları sorabilirsiniz.
Topluluk size yardım etmekten mutluluk duyacaktır.

=== Nasıl yardım edebilirim?

Birçok şekilde yardım edebilirsiniz:

- Belgelerde değişiklik yaparak çekme isteği(pull request) gönderebilirsiniz.
Yazım yanlışları ve küçük hatalar için GitHub arayüzünü kullanabilirsiniz ancak daha büyük ve karmaşık düzeltmeler için veri havuzunu bilgisayarınıza çekmeli, daha sonrasında düzeltmeleri yapıp çekme isteği göndermelisiniz.
Her iki durumda da kısa ve öz bir işleme mesajı(commit message) yazdığınıza emin olmalısınız.

- Eğer bir yanlış gördünüz ancak bir sebepten ötürü düzeltmeyi kendiniz yapmak istemediyseniz, bu hatayı bildirerek de yardım edebilirsiniz.
Bunun için veri havuzunun https://github.com/yazbel/belgeler/issues[konular(issues)] dizininde bir konu açın, başlık ve açıklama kısmına ilgili metinleri yazın ve gönderin.
Başlık kısmının kısa ve öz olmasına dikkat edin.
Ayrıca konuya, sağ taraftaki **Labels** bölümünden `beautiful-soup` etiketini eklediğinize de emin olun.

- https://forum.yazbel.com/c/python/beautiful-soup[Forumun Beautiful Soup kategorisi]nde sorulan soruları cevaplayabilirsiniz.

=== Lisans

https://github.com/yazbel/belgeler/blob/master/LICENSE[`LICENSE`] dosyasında da belirtildiği üzere bu belgelerin lisansı *Creative Commons Atıf-GayriTicari-AynıLisanslaPaylaş 4.0 Uluslararası (CC BY-NC-SA 4.0)* lisansıdır.
Daha fazla bilgi için lütfen dosyanın içeriğine bakınız.

== Beautiful Soup Hakkında

https://www.crummy.com/software/BeautifulSoup/[Beautiful Soup], XML ve HTML belgelerini işlemek için kullanılabilecek bir Python kütüphanesidir.
Beautiful Soup'u güçlü kılan üç özellik vardır:

. Beautiful Soup bir ayrıştırma ağacında gezinim, arama ve değiştirme yapmak için gerekli olan basit yordamları ve Pythonca deyimleri içerir.
Bu araçlar sayesinde bir belgeyi parçalarına ayırıp içinden istediklerinizi çıkartabilirsiniz.
. Beautiful Soup otomatik olarak, açılan dosyaları Unicode'a, kapanan dosyaları ise UTF-8'e çevirir.
Bu sebeple kodlama konusunda endişelenmenize gerek yoktur.
Sadece, eğer belge bir kodlama belirtmemişse özgün kodlamayı belirtmeniz gerekir.
. Beautiful Soup http://lxml.de/[lxml] ve https://github.com/html5lib/[html5lib] gibi gözde Python işleyicilerini kullanır, bu sebeple hız vb. sebeplerle farklı işleme taktiklerini kullanabilirsiniz.

Beautiful Soup'a bir belge gönderdikten sonra ona "Tüm bağlantıları bul.", "``ustBilgiBaglantisi`` sınıfına sahip tüm bağlantıları bul.", "Bağlantısı "``foo.com``"la eşleşen tüm bağlantıları bul." ya da "Kalın yazıya sahip çizelge başlığının yazısını ver." diyebilirsiniz.
Beautiful Soup, ayrıca, bozuk HTML ya da XML belgelerini de işleyebilmektedir.

== Kurulum

Şu an itibariyle en güncel Beautiful Soup sürümü Beautiful Soup 4'tür.
Beautiful Soup 4'ü kurmanın herkes için çalışacak en hızlı kurulum şekli `pip` ile kurmaktır:

[source,bash]
----
pip3 install beautifulsoup4
----
== QUİCK START

Bu bölümü atladım ilerde ekleriz.

== "Soup" İnşa Nesnesi oluşturalım

Bir dökümanı ayrıştırmadan(parse) önce beautifulsoup4 bizden bir Constructor yani bir inşa nesnesi oluşturmamızı isteyecek ,inşa aracının içinde string barındırabileceğimiz gibi bir dosyadan çağırdığımız verileride barındırabiliriz.
İçinde işleyeceğimiz verileri barındıran BeautifulSoup() nesnemizi çağıralım.

[source]
from bs4 import BeautifulSoup

Oluşturulan nesnemizi örnekleyerek işyeceğimiz verileri içine aktarıyoruz.

[source]
soup=BeautifulSoup(" <html>işlenecek veri</html> ")

Aktaracağımız verileri bir dosyadan okuyabileceğimizi de biliyorsunuz.

[source]

from bs4 import BeautifulSoup
with open("index.html") as fp:
  soup=BeautifulSoup(fp)

----
ekle: html dosyasındaki veriler işlenmeye hazırlanması için unicode ediliyor.
html tagları içindeki verilerde unicode karakterlerine dönüştürülüyor
----

Başlangıç tanımlamalarını yaptıktan sonra verilerimiz mevcut ayrıştırıcılarla en iyi şekilde işlenecektir.Bs4 kütüphanesi html ayrıştırma işlemlerinde kendi bünyesindeki ayrıştırıcıları kullanıyor olsa da isteğimiz doğrultusunda  bazı standart ve 3. parti moduller ile de uyumlu çalışmaktadır.
(XML Parser)


== Nesne Türleri

Beautiful Soup python un dizin ağacına html veri(document) dönüşümler yapmaktadır.Bu işlemler çoğu zaman karışık ve can sıkıcı olabilmektedir Bs kütüphanesinin bize sağladı bazı özellikler sayesinde biz sadece 4 çesit nesne ile ilgileneceğiz Bunlar;

. tag
. NavigableString
. BeautifulSoup
. Comment

---

=== Tag

Tag nesnesi orjinal dökümanda html veya xml ile haberleşmemizi sağlar.

[source]
soup=BeautifulSoup("<b class="boldest">Extremly Bold </b>")
tag=soup.b
type(tag)
#<class 'bs4.element.Tag'>

Tag'lar çeşitli nitelik ve metodlara sahip olabilir.İleri ki kısımlarda üstünden daha ayrıntılı geçeceğiz.Şimdi Tag'ların en önemli özelliklerinden olan name nedir ona geçelim.


=== Name

Her tag nesnesi bir isme sahiptir.bir tag'ın ismine ulaşmak için .name kullanılır.

[source]
tag.Name
#u'b'

Eğer bir tagın ismini değiştirirsek bu değişiklik tüm html yapısına yansıyacaktır tabiki Beautiful Soup sayesinde.

[source]
tag.name="mehmet"
tag.name
type(tag)

Böylece tag'ımızın yansımalarını daha iyi görebiliyoruz.

===  Attributes

Tag'larımız herzaman düşündüğümüz kadar sade bir yapıda olmayacaktır.İçinde birden fazla nitelik barındırabilir.Mesela <b id="boldest"> buradaki tag'ımız sadece id niteliği(attribute) almış değeri(value) ise "boldest" olarak tanımlanmış.
Bir tag'ın herhangi bir niteliğine ihtiyaç duyduğumuz zamanlarda  bu değerlere erişim sağlayabiliriz.
[source]

tag["id"]
#u'boldest'

gördüğünüz gibi önceki kısımlarda tanımladığımız tag'ı halen kullanabilmekteyiz üstelik id değerine ulaşabiliyoruz.Burdaki kullanımdan anlaşılacağı üzere tag isimlerimiz(name) birer sözlük şeklinde tutuluyor.Tüm bir sözlüğe ulaşmak için .attrs kullanalım:

[source]
tag.attrs
#{u'id':'boldest'}

Bir tag'ın niteliklerine erişim sağladık ve görüntüledik.Artık bi sözlük olarak elde ettiğimiz nitelikler üzerinde ekleme ve silme işlemi yapabiliriz.Gerekli iyileştirmeleri inceleyin ve kullanımına dair çıkarımda bulunun:

[source]
tag['id'='ahmet'
tag['baska-bir-nitelik']=1
# <b baska-bir-nitelik="1" id="ahmet"></b>

[source]
del tag['id']  #del silmek anlamına geliştirildikçe
del tag['baska-bir-nitelik']
tag
#<b></b>
tag['id']
#KeyError: 'id'
print(tag.get('id'))
#None


=== Multi-valued attributes

HTML 4 ile birlikte bir kaç nitelik birden fazla değer alabiliyordu.Html 5 yayınlanmasıyla çoklu değer tanımlamaları büyük ölçüde kaldırıldı ama halen kullanılmakta olanlar var.Bunlardan en yaygın kullanılanı "*class*"tır.
Özniteliklerin aldıkları değerler liste biçiminde tutulmaktadır.

[source]
css_soup = BeautifulSoup('<p class="body"></p>')
css_soup.p['class']
# ["body"]

css_soup.p tag alanına girdikten sonra class öğesine nasıl eriştiğimize dikkat edin.

[source]
css_soup = BeautifulSoup('<p class="body strikeout"></p>')
css_soup.p['class']
# ["body", "strikeout"]

Üstteki örneğin aksine classs niteliğimiz burada 2 değer almıştır aslında multiple-valued(birdenn fazla değere sahip olma) tam olarak bu örneğe karşılık geliyor.Çıktımıza dikkat ettiyseniz *body* ve *strikeout* değerlerinin nasıl listeli bir şekilde ayrıldığını gördünüz.Bu kullanıma sys.argv ve .split("") kullanımlarında da rastlanıyor.

Ayrı yazılan değerlerin her zaman multiple-valued olmadığını söylemekte fayda var.Aşağıdaki kod bloğunu bilgisayarımızda test edince beklendiği gibi bir liste ile karşılaşmadık.Bunun nedeni kısaca bahsettiğimiz html sürümlerinin tasarımından kaynaklanmaktadır.



[source]
id_soup = BeautifulSoup('<p id="my id"></p>')
id_soup.p['id']
# 'my id'

.Multiple-Valued Attributes Listesi
*rel,rev,charset,headers,accesskey*

[source]
rel_soup = BeautifulSoup('<p>Back to the <a rel="index">homepage</a></p>')
rel_soup.a['rel']
# ['index']
rel_soup.a['rel'] = ['index', 'contents']
print(rel_soup.p)
# <p>Back to the <a rel="index contents">homepage</a></p>

peki id örneğinde aldığımız tek değeri list halinde almak istersek ne yapacağız bunu temel python bilgimizle kolayca yapabilsekte beautiful soup bize *.get_attribute_list* kolaylığını sunmuştur.Hemen bir test edelim:

[source]

id_soup.p.get_attribute_list(‘id’)
 # [“my id”]

Aldığımız çıktıya dikkat edelim liste tipinde aldık bunu type() ile sizde görebilirsiniz.

==  Devam
